### ISSUE TITLE
Run `ruff check . --fix` before `pre-commit run --all-files` in CI

### ISSUE THREAD

**Issue by dr-rompecabezas** [OmdenaAI/GibdetColombiaChapter_UrbanTreeObservatory#105]
Add a step in the CI workflow to format files **before** the pre-commit hooks are executed. 

```yaml
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit ruff
    - name: Format files with ruff
      run: ruff check . --fix
    - name: Cache pre-commit hooks
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Run pre-commit hooks
      run: pre-commit run --all-files
```
